version: "3.3"
services:
  mongo:
    build: docker/mongo
    volumes:
      - mongodb_data:/data/db

    ports:
      - "27017:27017"
  node:
    build: docker/node
    volumes:
      - .:/usr/src/app
    ports:
      - "9001:8081"
    command: "nodemon ./bin/www.js"
    depends_on:
      - mongo
volumes:
  mongodb_data: